import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import LinkedinIcon from 'svgicon/linkedin.svg';
import GithubIcon from 'svgicon/github.svg';
import EmailIcon from 'svgicon/email.svg';
import Layout from 'Layout';
import FeedIcon from '@mui/icons-material/Feed';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a title="Linked in" href="https://www.linkedin.com/in/orenthal-hill/" target="_blank" rel="noreferrer">
        <LinkedinIcon />
      </a>

      <a title="Github" href="https://github.com/ojhill" target="_blank" rel="noreferrer">
        <GithubIcon />
      </a>
      <a href="mailto:ojhill98@gmail.com">
        <EmailIcon />
      </a>
      <a
        title="Resume"
        href="https://firebasestorage.googleapis.com/v0/b/oj-hill-portfolio.appspot.com/o/Orenthal_Hill_Resume.pdf?alt=media&token=2c5e50ab-e448-478c-ae8f-299d0ae28fd6"
        target="_blank"
        rel="noreferrer"
      >
        <FeedIcon fontSize="large" />
      </a>
    </Layout>
  );
}
